FROM node:20-alpine AS build

WORKDIR /app

# Package fájlok másolása
COPY package*.json ./
RUN npm install

# Forráskód másolása és build
COPY . .
RUN npm run build

# Production server
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]