version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"  
    container_name: beton_frontend
    platform: linux/arm64  

  mysql:
    image: mysql:8
    container_name: beton_mysql
    restart: always
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: beton_db
      MYSQL_USER: beton_user
      MYSQL_PASSWORD: beton123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: beton_phpmyadmin
    restart: always
    platform: linux/arm64
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - mysql

volumes:
  mysql_data: